name: Deploy docker image

on:
  push:
    branches:
      - 'develop'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
#     Set global environment variables:
      - name: set global env
        id: global_env
#       переменную IMAGE_NAME формируем из названия репозитория
#                       "owner/repo-name"
#       берем все что после   /  чтобы задать имя образа
#       set-output выставляет переменную в этом шаге
        run: |
          echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"

      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
      
      # - name: Docker login
      #   run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

    #   - name: Publish image
    #     env:
    #       IMAGE_NAME: $GITHUB_REPOSITORY
    #     run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/${{ steps.global_env.outputs.IMAGE_NAME }}"