name: Deploy docker image

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set global env
      id: global_env
      run: |
        echo "::set-output name=IMAGE_NAME::mflix"
        echo "::set-output name=DOCKERHUB_IMAGE_NAME::lestex/mflix"

    - name: Build and tag image
      run: |
        docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" \
        -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }}

    - name: Push image
      run: |
        docker push lestex/mflix:${GITHUB_SHA::8}
        docker push lestex/mflix:latest
